version: '3'

tasks:
  build:
    desc: "Build the application"
    dir: ./cmd/app
    cmds:
      - go build -o ../../bin/gocube.exe main.go

  run:
    desc: "Run the application"
    dir: ./cmd/app
    cmds:
      - go run main.go

  test:
    desc: "Run unit and integration tests with coverage"
    cmds:
      - go test ./... --tags=integration,unit -coverpkg=./...

  lint:
    desc: "Run linters and fix issues"
    cmds:
      - golangci-lint run --fix
